# ERP42Info
# State information for the ERP42 robot platform.

int32 longlCmdType  # Control method index

float32 position_x  # X position [m]
float32 position_y  # Y position [m]
float32 position_z  # Z position [m]

float32 roll  # Roll angle [deg]
float32 pitch  # Pitch angle [deg]
float32 yaw  # Yaw angle [deg]

float32 velocity  # Vehicle velocity [km/h]
float32 steering  # Steering angle [deg]
