std_msgs/Header header

int32[20] ego_index

float32[20] g_pos_x
float32[20] g_pos_y  
float32[20] g_pos_z

float32[20] g_roll
float32[20] g_pitch
float32[20] g_yaw

float32[20] velocity
uint8[20] gear
uint8[20] ctrl_mode

float32[20] steering_angle
float32[20] vehicle_speed
uint32[20] turn_signal
bool[20] brake_light

bool[20] is_kinematic

float32[20] driver_aps
float32[20] driver_bps

float32[20] remaining_dist