Header header

float64 ego_acc
float64 ego_brake
float64 ego_steer

float64 ego_orientation_x
float64 ego_orientation_y
float64 ego_orientation_z
float64 ego_orientation_w

float64 ego_linearAcceleration_x
float64 ego_linearAcceleration_y
float64 ego_linearAcceleration_z

float64 ego_AngularVelocity_x
float64 ego_AngularVelocity_y
float64 ego_AngularVelocity_z

int32 num_of_objects
int16[] object_type

int32[] object_id

float64[] pose_x
float64[] pose_y
float64[] pose_z

float64[] heading

float64[] size_x
float64[] size_y
float64[] size_z

float64[] velocity

